substitutions:
  _IMAGE: 'us-central1-docker.pkg.dev/cloudside-academy/Python-Flask-Deployment/python-deployment'
  _SERVICE_NAME: 'python-flask-service'
  _REGION: 'us-central1'


steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=${_IMAGE}'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
 options:
  logging: CLOUD_LOGGING_ONLY

