substitutions:
  _IMAGE: 'us-central1-docker.pkg.dev/cloudside-academy/python-flask-deployment/python-deployment'
  _SERVICE_NAME: 'python-flask-service'
  _REGION: 'us-central1'

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE}', '.']
    dir: 'prediction_Expense'  # Correct the directory to where your Dockerfile is located

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE}']

  # Step 3: Deploy the image to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=${_IMAGE}'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY
